name = "InteractiveDataLanguage"
uuid = "d8fbff9c-ffdd-4f12-b08d-aa41cc43ce74"
version = "0.3.0"
authors = ["Camillo Schenone"]

[workspace]
projects = ["test", "gen"]

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
CEnum = "0.5.0"
REPL = "1.11.0"
StaticArrays = "1.9.15"
julia = "1.12"
