[general]
library_name = "libidl"

output_file_path = "../lib/lib_idl-v2.jl"
prologue_file_path = ""
epilogue_file_path = ""

use_julia_native_enum_type = true
print_using_CEnum = false

export_symbol_prefixes = []

[codegen]
add_record_constructors = true